# -*- coding: utf-8 -*-
"""Functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wbpW8l_YVAHRPW4NiI8nDdRTNVua9YN
"""

def greet():
    print("Hello! Welcome to Python Functions.")

# Calling the function
greet()

def greet(age):
    print(f"ALia is, {age} years old")

greet("12")
greet(18)

def greet_user(name="Guest"):
    print(f"Welcome, {name}!")

greet_user()         # Uses default
greet_user("Ravi")

def print_names(*names):
    print("Names passed:", names)
    for name in names:
        print("Hello", name)

print_names("Alice", "bob", "Charlie")

def print_info(**info):
    print("User Info:")
    for key, value in info.items():
        print(f"{key} = {value}")

print_info(name="Alice", age=25, city="Delhi")

def multiply(a, b):
    return a * b

def square(n):
    return multiply(n, n)

print("Square of 4:", square(4))